# Generated by Django 5.1.7 on 2025-03-28 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_type', models.CharField(choices=[('BID', 'Buy Order'), ('ASK', 'Sell Order')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ask_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_trades', to='trading.order')),
                ('ask_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_trades', to=settings.AUTH_USER_MODEL)),
                ('bid_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_trades', to='trading.order')),
                ('bid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'price', 'is_active'], name='trading_ord_order_t_d50f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'is_active'], name='trading_ord_user_id_1501e9_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['timestamp'], name='trading_tra_timesta_38f861_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['bid_user'], name='trading_tra_bid_use_f63b42_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['ask_user'], name='trading_tra_ask_use_a3fb94_idx'),
        ),
    ]
