# Generated by Django 5.1.7 on 2025-03-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='taker_side',
            field=models.CharField(choices=[('BID', 'Bid was taker'), ('ASK', 'Ask was taker')], default='BID', max_length=3),
        ),
    ]
