# Generated by Django 5.1.7 on 2025-03-29 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_order_price_alter_order_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='trading_ord_order_t_d50f9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='trading_ord_user_id_1501e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='trading_tra_timesta_38f861_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='trading_tra_bid_use_f63b42_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='trading_tra_ask_use_a3fb94_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'is_active', 'price', 'timestamp'], name='idx_ask_matching'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'is_active', '-price', 'timestamp'], name='idx_bid_matching'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['-timestamp'], name='idx_trade_time'),
        ),
    ]
